[package]
name = "bot"
version = "1.0.0"
edition = "2024"

[dependencies]
envy = "0.4"
telers = { git = "https://github.com/Desiders/telers.git", rev = "66cce11018f9f3e8b4218697413d90e4c7253825", features = ["default_signal"] }
tokio = { version = "1.36", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
once_cell = "1"
thiserror = "2.0"
toml = "0.8"
