cargo-features = ["edition2024"]

[package]
name = "bot"
version = "1.0.0"
edition = "2024"

[dependencies]
telers = { version = "1.0.0-alpha.25", features = ["default_signal"] }
tokio = { version = "1.36", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
toml = "0.8"
